services:
    ControleOnline\:
        resource: "../../vendor/controleonline/financial/src/*"
        exclude: "../../vendor/controleonline/common/src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}"
