services:
    ControleOnline\:
        resource: "../../vendor/controleonline/financial/src/*"
        exclude: "../src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}"
    ControleOnline\Repository\:
        resource: "../../vendor/controleonline/financial/src/Repository"
        tags: ["doctrine.repository_service"]
        arguments:
            $registry: '@doctrine'   
            
    ControleOnline\Controller\:
        resource: "../../vendor/controleonline/financial/src/Controller"
        tags: ["controller.service_arguments"]                