services:
    ControleOnline\:
        resource: "../../vendor/controleonline/queue/src/*"
        exclude: "../src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}"
    ControleOnline\Repository\:
        resource: "../../vendor/controleonline/queue/src/Repository"
        tags: ["doctrine.repository_service"]
        arguments:
            $registry: '@doctrine'        

 