parameters:
    env(VARNISH_URL): ""

api_platform:
    enable_re_doc: true
    enable_swagger_ui: true
    defaults:
        normalization_context:
            enable_max_depth: true
        skip_null_values: true
        pagination_client_items_per_page: true
        extra_properties:
            standard_put: false
    formats:
        jsonld: ["application/ld+json"]
        jsonhal: ["application/hal+json"]
        jsonapi: ["application/vnd.api+json"]
        json: ["application/json"]
        xml: ["application/xml", "text/xml"]
        yaml: ["application/x-yaml"]
        csv: ["text/csv"]
        css: ["text/css"]
        html: ["text/html"]
    mapping:
        paths:
            - "%kernel.project_dir%/src/Entity"
            - "%kernel.project_dir%/src/Resource"
    title: API
    show_webby: false
    version: 1.0.0
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
    graphql:
        graphiql:
            enabled: true
    eager_loading:
        max_joins: 100
