doctrine:
    dbal:
        # configure these for your database server
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
        url: "%env(resolve:DATABASE_URL)%"
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        mapping_types:
            enum: string
        options:
            1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""));SET TRANSACTION ISOLATION LEVEL READ COMMITTED;'
    orm:
        dql:
            numeric_functions:
                acos: DoctrineExtensions\Query\Mysql\Acos
                cos: DoctrineExtensions\Query\Mysql\Cos
                sin: DoctrineExtensions\Query\Mysql\Sin
                pi: DoctrineExtensions\Query\Mysql\Pi
                rand: DoctrineExtensions\Query\Mysql\Rand
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
            Products:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/products/src/Entity"
                prefix: 'Controleonline\Entity'
                alias: ControleOnline
            Users:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/users/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            Financial:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/financial/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            Contract:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/contract/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline

            Tasks:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/tasks/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline

            Dashboard:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/dashboard/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            People:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/people/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            Ead:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/ead/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            Queue:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/queue/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            Quote:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/quote/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            Common:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/common/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
            Orders:
                is_bundle: false
                type: annotation
                dir: "%kernel.project_dir%/vendor/controleonline/orders/src/Entity"
                prefix: 'ControleOnline\Entity'
                alias: ControleOnline
