# config/packages/gos_web_socket.yaml
gos_web_socket:
    server:
        # The host IP address on the server which connections for the websocket server are accepted.
        host: 127.0.0.1

        # The port on the server which connections for the websocket server are accepted.
        port: 8080

        router:
            resources:
                -
                    resource: '%kernel.project_dir%/var/cache/websocket/*'
                    type: 'glob'        
    pushers:
        wamp:                 # Deprecated (Since gos/web-socket-bundle 3.1: The child node "wamp" at path "gos_web_socket.pushers" is deprecated and will be removed in GosWebSocketBundle 4.0. Use the symfony/messenger component instead.)
            enabled:              true
            host:                 127.0.0.1 # Required
            port:                 8080 # Required
            ssl:                  false
            origin:               null                        