framework:
    messenger:
        transports:
            iFood:
                dsn: "doctrine://default"
                options:
                    table_name: integration
                    queue_name: iFood
        routing:
            'ControleOnline\Message\iFood\OrderMessage': iFood
