security:
    password_hashers:
        ControleOnline\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: ControleOnline\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - ControleOnline\Security\TokenAuthenticator
            json_login:
                check_path: /token
                username_path: username
                password_path: password

    role_hierarchy:
        ROLE_SUPER: ROLE_SUPER
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_CLIENT: ROLE_CLIENT

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/docs$, roles: PUBLIC_ACCESS }
        - { path: ^/token$, roles: PUBLIC_ACCESS }
        - { path: ^/themes-colors.css$, roles: PUBLIC_ACCESS }
        - { path: ^/languages$, roles: PUBLIC_ACCESS }
        - { path: ^/people/company/default$, roles: PUBLIC_ACCESS }
        - { path: ^/translates$, roles: PUBLIC_ACCESS }
        - { path: ^/cart$, roles: PUBLIC_ACCESS }
        - { path: ^/files/.*$, roles: PUBLIC_ACCESS }
        - { path: ^/webhook/, roles: PUBLIC_ACCESS }
        - { path: ^/oauth/, roles: PUBLIC_ACCESS }
        - { path: ^/pix$, roles: PUBLIC_ACCESS }
        - { path: ^/bitcoin$, roles: PUBLIC_ACCESS }
        - { path: ^/categories$, roles: PUBLIC_ACCESS }
        - { path: ^/products$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
