security:
    password_hashers:
        ControleOnline\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: ControleOnline\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - ControleOnline\Security\TokenAuthenticator
            json_login:
                check_path: /token
                username_path: username
                password_path: password

    role_hierarchy:
        ROLE_SUPER: ROLE_ADMIN
        ROLE_ADMIN: ROLE_CLIENT
        ROLE_CLIENT: ROLE_USER

    access_control:
        - { path: ^/my_contracts/signatures-finished, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
