controllers:
    resource: ../../src/Controller/
    type: annotation
controleonline_users:
    resource: ../../modules/controleonline/users/src/Controller/
    type: annotation
controleonline_financial:
    resource: ../../modules/controleonline/financial/src/Controller/
    type: annotation
controleonline_orders:
    resource: ../../modules/controleonline/orders/src/Controller/
    type: annotation