controllers:
    resource: ../../src/Controller/
    type: annotation

users:
    resource: "../../vendor/controleonline/users/src/Controller/"
    type: annotation
    tags: ["controller.service_arguments"]
    arguments:
        $entityManager: "@doctrine.orm.default_entity_manager"
