imports:
    - { resource: "../vendor/controleonline/products/config/config.yaml" }
    - { resource: "../vendor/controleonline/common/config/config.yaml" }
    - { resource: "../vendor/controleonline/financial/config/config.yaml" }
    - { resource: "../vendor/controleonline/contract/config/config.yaml" }
    - { resource: "../vendor/controleonline/dashboard/config/config.yaml" }
    - { resource: "../vendor/controleonline/ead/config/config.yaml" }
    - { resource: "../vendor/controleonline/orders/config/config.yaml" }
    - { resource: "../vendor/controleonline/people/config/config.yaml" }
    - { resource: "../vendor/controleonline/queue/config/config.yaml" }
    - { resource: "../vendor/controleonline/quote/config/config.yaml" }
    - { resource: "../vendor/controleonline/users/config/config.yaml" }