#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# authentication_token:
#     path   : /authentication_token
#     methods: ['POST']

graphiql:
    path      : /docs/graphiql
    controller: api_platform.graphql.action.graphiql

graphql_playground:
    path      : /docs/graphql_playground
    controller: api_platform.graphql.action.graphql_playground



connect_google_start:
    path: '/oauth/google/connect'
    controller: 'ControleOnline\Controller\Oauth\GoogleController::connectAction'

connect_google_return:
    path: '/oauth/google/return'
    controller: 'ControleOnline\Controller\Oauth\GoogleController::returnAction'
    methods: ['GET', 'POST']