name: Deploy Project
on:
  push:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"                          
      - name: Update Controle Online      
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.CONTROLEONLINE }}
          port: ${{ secrets.PORT }}        
          script: |
                  cd ~/sistemas/controleonline/api
                  git checkout production
                  git pull origin production    
                  git submodule update --recursive --init
                  git submodule update --recursive --remote        
                  composer install --no-suggest
                  php bin/console tenant:migrations:migrate --no-interaction                                   
