name: Deploy Project
on:
  push:
    branches: [develop,master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"         
      - name: Creating Config
        run: |
          mkdir -p ./var/cache/
          touch ./var/cache/websocket
      - name: Update Submodules
        run: |                 
          git submodule update --recursive --init
          git submodule update --recursive --remote
          composer install --no-suggest
          cd ..
          tar -czf api.tar.gz ./api-community
          cd ./api-community
          mkdir deploy
          mv ./../api.tar.gz ./deploy
      - name: Deploy
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.DEV_HOST }}
          user: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASS }}
          localDir: "./deploy"
          remoteDir: "~/sistemas"
          forceSsl: false                             
